import React, { createContext, useContext, useReducer, useEffect } from "react";

const AppContext = createContext();

const initialState = {
  // Auth
  isAdminAuthenticated: false,
  currentUser: null,

  // Comprehensive Firearms Collection
  products: [
    {
      id: 1,
      name: "Glock 19 Gen 5",
      description:
        "The most versatile and reliable compact pistol for concealed carry, home defense, and duty use. Features enhanced ergonomics and improved accuracy.",
      price: 549.99,
      originalPrice: 599.99,
      category: "handguns",
      stock: 15,
      images: [
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "Glock",
      caliber: "9mm Luger",
      capacity: "15+1",
      barrelLength: "4.02 inches",
      overallLength: "7.36 inches",
      weight: "23.65 oz",
      action: "Safe Action",
      finish: "Polymer Frame / Steel Slide",
      sights: "Glock Night Sights",
      features: [
        "Enhanced trigger with smoother pull",
        "Improved grip texture",
        "Ambidextrous slide stop lever",
        "Flared magazine well",
        "No finger grooves",
      ],
      specifications: {
        frameSize: "Compact",
        triggerPull: "5.5 lbs",
        safetyFeatures: ["Trigger Safety", "Firing Pin Safety", "Drop Safety"],
        magazines: "Ships with 3 magazines",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.8,
      reviews: 247,
    },
    {
      id: 11,
      name: "Sig Sauer P320",
      description:
        "Modular striker-fired pistol system adopted by the U.S. Military. Ultimate in reliability and versatility.",
      price: 629.99,
      originalPrice: 699.99,
      category: "handguns",
      stock: 12,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "Sig Sauer",
      caliber: "9mm Luger",
      capacity: "17+1",
      barrelLength: "4.7 inches",
      overallLength: "8.0 inches",
      weight: "29.4 oz",
      action: "Striker Fired",
      finish: "Nitron Stainless Steel",
      sights: "SIGLITE Night Sights",
      features: [
        "Modular design allows caliber changes",
        "Enhanced trigger with crisp break",
        "Accessory rail for lights/lasers",
        "Removable fire control unit",
        "Tool-free disassembly",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "5.5-6.5 lbs",
        safetyFeatures: ["Striker Safety", "Disconnect Safety"],
        magazines: "Ships with 2 magazines",
        warranty: "Lifetime Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 189,
    },
    {
      id: 12,
      name: "Smith & Wesson M&P Shield Plus",
      description:
        "Ultra-compact concealed carry pistol with increased capacity. Perfect balance of size and shootability.",
      price: 499.99,
      category: "handguns",
      stock: 20,
      images: [
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Smith & Wesson",
      caliber: "9mm Luger",
      capacity: "13+1",
      barrelLength: "3.1 inches",
      overallLength: "6.1 inches",
      weight: "20.2 oz",
      action: "Striker Fired",
      finish: "Armornite Coating",
      sights: "White Dot Front / Adjustable Rear",
      features: [
        "Flat face trigger for consistent pull",
        "Aggressive grip texture",
        "Low profile carry sights",
        "Enhanced magazine release",
        "Optics ready version available",
      ],
      specifications: {
        frameSize: "Sub-Compact",
        triggerPull: "6.5 lbs",
        safetyFeatures: [
          "Trigger Safety",
          "Firing Pin Safety",
          "Magazine Safety",
        ],
        magazines: "Ships with 2 magazines",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.6,
      reviews: 156,
    },
    {
      id: 13,
      name: "Springfield XD-M Elite",
      description:
        "Competition-grade pistol with match barrel and enhanced ergonomics. Precision meets performance.",
      price: 749.99,
      originalPrice: 829.99,
      category: "handguns",
      stock: 8,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "Springfield Armory",
      caliber: "9mm Luger",
      capacity: "20+1",
      barrelLength: "4.5 inches",
      overallLength: "7.6 inches",
      weight: "31 oz",
      action: "Striker Fired",
      finish: "Melonite Treatment",
      sights: "Fiber Optic Front / Adjustable Rear",
      features: [
        "Match grade barrel",
        "Enhanced grip texturing",
        "Ambidextrous magazine release",
        "Striker status indicator",
        "Loaded chamber indicator",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "5.5-7.7 lbs",
        safetyFeatures: ["Grip Safety", "Trigger Safety", "Firing Pin Safety"],
        magazines: "Ships with 3 magazines",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.5,
      reviews: 98,
    },
    {
      id: 14,
      name: "Walther PDP",
      description:
        "Performance Duty Pistol engineered for superior ergonomics and accuracy. The evolution of excellence.",
      price: 679.99,
      category: "handguns",
      stock: 10,
      images: [
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Walther",
      caliber: "9mm Luger",
      capacity: "18+1",
      barrelLength: "4.0 inches",
      overallLength: "7.4 inches",
      weight: "27 oz",
      action: "Striker Fired",
      finish: "Tenifer Coating",
      sights: "Performance Duty Sights",
      features: [
        "Performance Duty Trigger",
        "SuperTerrain Slide Serrations",
        "Optics-ready slide",
        "Ambidextrous slide stop",
        "Enhanced Performance Duty Texture",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "5.6 lbs",
        safetyFeatures: ["Trigger Safety", "Firing Pin Safety", "Drop Safety"],
        magazines: "Ships with 2 magazines",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.7,
      reviews: 73,
    },
    {
      id: 15,
      name: "Ruger Security-9",
      description:
        "Affordable, reliable striker-fired pistol perfect for new shooters and budget-conscious buyers.",
      price: 379.99,
      category: "handguns",
      stock: 25,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Ruger",
      caliber: "9mm Luger",
      capacity: "15+1",
      barrelLength: "4.0 inches",
      overallLength: "7.24 inches",
      weight: "23.7 oz",
      action: "Striker Fired",
      finish: "Blued Steel",
      sights: "Drift Adjustable 3-Dot",
      features: [
        "Secure Action trigger system",
        "Ergonomic grip frame",
        "Safety paddle magazine release",
        "Genuine Novak LoMount Carry sight",
        "Picatinny rail",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "6.0 lbs",
        safetyFeatures: [
          "Trigger Safety",
          "Manual Safety",
          "Magazine Disconnect",
        ],
        magazines: "Ships with 2 magazines",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.3,
      reviews: 142,
    },
    {
      id: 16,
      name: "HK VP9",
      description:
        "German-engineered striker-fired pistol with customizable grip and exceptional accuracy.",
      price: 799.99,
      originalPrice: 899.99,
      category: "handguns",
      stock: 6,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "Heckler & Koch",
      caliber: "9mm Luger",
      capacity: "15+1",
      barrelLength: "4.09 inches",
      overallLength: "7.34 inches",
      weight: "26.56 oz",
      action: "Striker Fired",
      finish: "Hostile Environment Finish",
      sights: "3-Dot Luminous",
      features: [
        "Customizable grip with panels",
        "HK Light Strike ignition system",
        "Ambidextrous controls",
        "Cold hammer-forged barrel",
        "No external safety",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "5.4 lbs",
        safetyFeatures: ["Drop Safety", "Firing Pin Safety"],
        magazines: "Ships with 3 magazines",
        warranty: "HK Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.8,
      reviews: 201,
    },
    {
      id: 17,
      name: "CZ P-10C",
      description:
        "Czech-made striker-fired pistol with exceptional trigger and unmatched reliability.",
      price: 599.99,
      category: "handguns",
      stock: 14,
      images: [
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "CZ-USA",
      caliber: "9mm Luger",
      capacity: "15+1",
      barrelLength: "4.02 inches",
      overallLength: "7.3 inches",
      weight: "26 oz",
      action: "Striker Fired",
      finish: "Nitride",
      sights: "Metal 3-Dot",
      features: [
        "Best-in-class trigger",
        "Interchangeable backstraps",
        "Fiber-reinforced polymer frame",
        "Reversible magazine release",
        "Superior ergonomics",
      ],
      specifications: {
        frameSize: "Compact",
        triggerPull: "4.5-5.0 lbs",
        safetyFeatures: ["Firing Pin Safety", "Trigger Safety"],
        magazines: "Ships with 2 magazines",
        warranty: "5 Year Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.6,
      reviews: 167,
    },
    {
      id: 18,
      name: "Beretta 92FS",
      description:
        "Classic full-size pistol used by military and law enforcement worldwide. Proven reliability and accuracy.",
      price: 679.99,
      originalPrice: 749.99,
      category: "handguns",
      stock: 9,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&auto=format",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "Beretta",
      caliber: "9mm Luger",
      capacity: "15+1",
      barrelLength: "4.9 inches",
      overallLength: "8.5 inches",
      weight: "33.3 oz",
      action: "Double/Single Action",
      finish: "Bruniton",
      sights: "3-Dot",
      features: [
        "Open-slide design",
        "Chrome-lined barrel",
        "Ambidextrous safety",
        "Reversible magazine release",
        "Combat trigger guard",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "12 lbs DA / 4.5 lbs SA",
        safetyFeatures: ["Manual Safety", "Firing Pin Block"],
        magazines: "Ships with 2 magazines",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 312,
    },
    {
      id: 19,
      name: "Kimber Ultra Carry II",
      description:
        "Premium 1911-style compact pistol with enhanced features for concealed carry.",
      price: 899.99,
      category: "handguns",
      stock: 5,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop&auto=format",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Kimber",
      caliber: ".45 ACP",
      capacity: "7+1",
      barrelLength: "3.0 inches",
      overallLength: "6.8 inches",
      weight: "25 oz",
      action: "Single Action Only",
      finish: "Satin Silver",
      sights: "Fixed Low Profile",
      features: [
        "Aluminum frame construction",
        "Match grade barrel",
        "Full-length guide rod",
        "High-ride beavertail",
        "Carry melt treatment",
      ],
      specifications: {
        frameSize: "Compact",
        triggerPull: "4-5 lbs",
        safetyFeatures: ["Manual Thumb Safety", "Grip Safety"],
        magazines: "Ships with 2 magazines",
        warranty: "Kimber Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.4,
      reviews: 87,
    },
    {
      id: 20,
      name: "Taurus G3C",
      description:
        "Affordable and reliable striker-fired compact pistol perfect for concealed carry and home defense.",
      price: 299.99,
      category: "handguns",
      stock: 22,
      images: [
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&auto=format",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Taurus",
      caliber: "9mm Luger",
      capacity: "12+1",
      barrelLength: "3.2 inches",
      overallLength: "6.3 inches",
      weight: "22 oz",
      action: "Striker Fired",
      finish: "Black Polymer",
      sights: "Adjustable Rear",
      features: [
        "Striker block system",
        "Manual safety",
        "Memory pads",
        "Restrike capability",
        "Loaded chamber indicator",
      ],
      specifications: {
        frameSize: "Compact",
        triggerPull: "6.0 lbs",
        safetyFeatures: ["Manual Safety", "Trigger Safety", "Firing Pin Block"],
        magazines: "Ships with 2 magazines",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.2,
      reviews: 198,
    },
    {
      id: 21,
      name: "FN 509 Tactical",
      description:
        "Optics-ready tactical pistol with suppressor-ready threaded barrel. Built for professionals.",
      price: 899.99,
      originalPrice: 999.99,
      category: "handguns",
      stock: 7,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop&auto=format",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "FN America",
      caliber: "9mm Luger",
      capacity: "24+1",
      barrelLength: "4.5 inches",
      overallLength: "8.15 inches",
      weight: "27.9 oz",
      action: "Striker Fired",
      finish: "FDE Polymer Frame",
      sights: "Suppressor Height Night Sights",
      features: [
        "Optics-ready slide",
        "Threaded barrel",
        "Enhanced grip texture",
        "Ambidextrous controls",
        "Low-profile slide stop",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "5.5-7.7 lbs",
        safetyFeatures: ["Trigger Safety", "Firing Pin Safety"],
        magazines: "Ships with 3 magazines (24rd)",
        warranty: "FN Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.6,
      reviews: 143,
    },
    {
      id: 22,
      name: "Desert Eagle .50 AE",
      description:
        "Iconic large-caliber semi-automatic pistol. The ultimate in stopping power and prestige.",
      price: 1899.99,
      category: "handguns",
      stock: 3,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop&auto=format",
      ],
      featured: true,
      displayLocation: ["home", "featured", "handguns"],
      manufacturer: "Magnum Research",
      caliber: ".50 Action Express",
      capacity: "7+1",
      barrelLength: "6.0 inches",
      overallLength: "10.75 inches",
      weight: "70.5 oz",
      action: "Semi-Automatic",
      finish: "Black Oxide",
      sights: "Fixed Combat",
      features: [
        "Gas-operated action",
        "Rotating bolt system",
        "Polygonal rifling",
        "Weaver rail system",
        "Iconic design",
      ],
      specifications: {
        frameSize: "Large Frame",
        triggerPull: "4.0 lbs",
        safetyFeatures: ["Manual Safety", "Firing Pin Safety"],
        magazines: "Ships with 1 magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.3,
      reviews: 76,
    },
    {
      id: 23,
      name: "Canik TP9SFx",
      description:
        "Competition-ready striker-fired pistol with superior ergonomics and match-grade trigger.",
      price: 459.99,
      category: "handguns",
      stock: 16,
      images: [
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop&auto=format",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Canik",
      caliber: "9mm Luger",
      capacity: "20+1",
      barrelLength: "5.2 inches",
      overallLength: "8.5 inches",
      weight: "29.9 oz",
      action: "Striker Fired",
      finish: "Tungsten Cerakote",
      sights: "Fiber Optic Front / Adjustable Rear",
      features: [
        "Competition trigger",
        "Optics-ready slide",
        "Interchangeable backstraps",
        "Extended magazine release",
        "Flared magazine well",
      ],
      specifications: {
        frameSize: "Full Size",
        triggerPull: "3.5-4.0 lbs",
        safetyFeatures: ["Trigger Safety", "Firing Pin Safety", "Drop Safety"],
        magazines: "Ships with 2 magazines (20rd)",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.7,
      reviews: 224,
    },
    {
      id: 24,
      name: "Mossberg MC2c",
      description:
        "Compact carry pistol designed for everyday carry with enhanced grip texture and reliable performance.",
      price: 449.99,
      category: "handguns",
      stock: 11,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop&auto=format",
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop&auto=format",
      ],
      featured: false,
      displayLocation: ["handguns"],
      manufacturer: "Mossberg",
      caliber: "9mm Luger",
      capacity: "13+1",
      barrelLength: "3.9 inches",
      overallLength: "7.1 inches",
      weight: "21 oz",
      action: "Striker Fired",
      finish: "Black DLC",
      sights: "3-Dot",
      features: [
        "Aggressive grip texturing",
        "Flat-faced trigger",
        "Cross-bolt safety",
        "SIG optics compatibility",
        "Enhanced slide serrations",
      ],
      specifications: {
        frameSize: "Compact",
        triggerPull: "5.5-6.5 lbs",
        safetyFeatures: [
          "Cross-Bolt Safety",
          "Trigger Safety",
          "Firing Pin Block",
        ],
        magazines: "Ships with 2 magazines",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.1,
      reviews: 64,
    },
    // RIFLES COLLECTION
    {
      id: 2,
      name: "Smith & Wesson M&P15 Sport II",
      description:
        "America's most popular modern sporting rifle. Reliable, accurate, and versatile for hunting, competition, and recreational shooting.",
      price: 899.99,
      originalPrice: 999.99,
      category: "rifles",
      stock: 8,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "rifles"],
      manufacturer: "Smith & Wesson",
      caliber: "5.56 NATO/.223 Remington",
      capacity: "30 rounds (10-round compliant available)",
      barrelLength: "16 inches",
      overallLength: "32-35 inches",
      weight: "6.5 lbs",
      action: "Semi-Automatic",
      finish: "Matte Black Armornite",
      sights: "Adjustable A2 Post Front / Dual Aperture Rear",
      features: [
        "Chromed firing pin",
        "Forward assist",
        "Dust cover",
        "Picatinny rail",
        "6-position telescoping stock",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "6.5 lbs",
        safetyFeatures: ["Manual Safety", "Half-Cock Notch"],
        magazines: "Ships with 1 magazine",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 342,
    },
    {
      id: 17,
      name: "Ruger 10/22 Carbine",
      description:
        "America's favorite .22 rifle. Perfect for beginners, training, and small game hunting with legendary reliability.",
      price: 349.99,
      category: "rifles",
      stock: 15,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "rifles"],
      manufacturer: "Ruger",
      caliber: ".22 Long Rifle",
      capacity: "10 rounds",
      barrelLength: "18.5 inches",
      overallLength: "37 inches",
      weight: "5.0 lbs",
      action: "Semi-Automatic",
      finish: "Satin Black",
      sights: "Gold Bead Front / Folding Rear",
      features: [
        "Patented 10-round rotary magazine",
        "Cold hammer-forged barrel",
        "Extended magazine release",
        "Ergonomic stock design",
        "Easy takedown for cleaning",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "6.0 lbs",
        safetyFeatures: ["Manual Cross-Bolt Safety"],
        magazines: "Ships with 1 rotary magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.8,
      reviews: 156,
    },
    {
      id: 18,
      name: "Remington 700 SPS",
      description:
        "The most trusted bolt-action rifle platform for hunting and precision shooting. Legendary accuracy since 1962.",
      price: 649.99,
      originalPrice: 729.99,
      category: "rifles",
      stock: 6,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Remington",
      caliber: ".308 Winchester",
      capacity: "4+1",
      barrelLength: "24 inches",
      overallLength: "46.5 inches",
      weight: "8.5 lbs",
      action: "Bolt-Action",
      finish: "Matte Black",
      sights: "None - Drilled & Tapped for Scope",
      features: [
        "Free-floating barrel",
        "Two-stage trigger",
        "Hinged floorplate",
        "Synthetic stock",
        "Pillar bedded action",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "3.5-5.0 lbs adjustable",
        safetyFeatures: ["3-Position Safety"],
        magazines: "Internal magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.6,
      reviews: 89,
    },
    {
      id: 19,
      name: "Winchester Model 70 Featherweight",
      description:
        "The rifleman's rifle. Classic American design with modern manufacturing for hunting excellence.",
      price: 1049.99,
      category: "rifles",
      stock: 4,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Winchester",
      caliber: ".270 Winchester",
      capacity: "5+1",
      barrelLength: "22 inches",
      overallLength: "42.7 inches",
      weight: "6.75 lbs",
      action: "Bolt-Action",
      finish: "Matte Blued",
      sights: "None - Drilled & Tapped",
      features: [
        "Controlled round feed",
        "Three-position safety",
        "Walnut stock",
        "MOA trigger system",
        "Free-floating barrel",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "3.5-5.0 lbs",
        safetyFeatures: ["3-Position M.O.A. Trigger"],
        magazines: "Fixed magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.9,
      reviews: 67,
    },
    {
      id: 20,
      name: "Marlin Model 336 Lever Action",
      description:
        "Classic American lever-action rifle perfect for deer hunting and brush country. Fast follow-up shots with reliability.",
      price: 599.99,
      originalPrice: 649.99,
      category: "rifles",
      stock: 10,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["rifles"],
      manufacturer: "Marlin",
      caliber: ".30-30 Winchester",
      capacity: "6+1",
      barrelLength: "20 inches",
      overallLength: "38.5 inches",
      weight: "7.0 lbs",
      action: "Lever-Action",
      finish: "Blued Steel",
      sights: "Brass Bead Front / Semi-Buckhorn Rear",
      features: [
        "Side ejection for scope mounting",
        "Solid-top receiver",
        "Hammer block safety",
        "American black walnut stock",
        "Tapped for scope mounts",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "4.5-6.0 lbs",
        safetyFeatures: ["Hammer Block Safety", "Half-Cock Position"],
        magazines: "Tubular magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 124,
    },
    {
      id: 21,
      name: "Savage Arms 110 Hunter",
      description:
        "Precision rifle engineered for accuracy with user-adjustable AccuTrigger and button-rifled barrel.",
      price: 449.99,
      category: "rifles",
      stock: 12,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Savage Arms",
      caliber: ".243 Winchester",
      capacity: "4+1",
      barrelLength: "22 inches",
      overallLength: "43.25 inches",
      weight: "7.5 lbs",
      action: "Bolt-Action",
      finish: "Matte Black",
      sights: "None - Drilled & Tapped",
      features: [
        "User-adjustable AccuTrigger",
        "Button-rifled barrel",
        "Synthetic AccuStock",
        "Soft grip surfaces",
        "Detachable box magazine",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "2.5-6.0 lbs adjustable",
        safetyFeatures: ["AccuTrigger Safety", "Tang Safety"],
        magazines: "Ships with 1 detachable magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.5,
      reviews: 78,
    },
    {
      id: 22,
      name: "Henry Big Boy Steel",
      description:
        "Modern lever-action with steel receiver and side loading gate. Perfect blend of tradition and innovation.",
      price: 899.99,
      originalPrice: 979.99,
      category: "rifles",
      stock: 7,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Henry Repeating Arms",
      caliber: ".357 Magnum/.38 Special",
      capacity: "10+1",
      barrelLength: "20 inches",
      overallLength: "38.5 inches",
      weight: "7.08 lbs",
      action: "Lever-Action",
      finish: "Blued Steel",
      sights: "Brass Bead Front / Semi-Buckhorn Rear",
      features: [
        "Steel receiver",
        "Side loading gate",
        "Octagon barrel",
        "American walnut stock",
        "Transfer bar safety",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "4.0-5.0 lbs",
        safetyFeatures: ["Transfer Bar Safety", "Half-Cock Position"],
        magazines: "Tubular magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.8,
      reviews: 56,
    },
    {
      id: 23,
      name: "Tikka T3x Hunter",
      description:
        "Finnish precision engineering meets hunting performance. Exceptional accuracy in a lightweight package.",
      price: 749.99,
      category: "rifles",
      stock: 5,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Tikka",
      caliber: ".30-06 Springfield",
      capacity: "3+1",
      barrelLength: "22.4 inches",
      overallLength: "42.9 inches",
      weight: "6.3 lbs",
      action: "Bolt-Action",
      finish: "Matte Stainless",
      sights: "None - Drilled & Tapped",
      features: [
        "Cold hammer-forged barrel",
        "Smooth bolt operation",
        "Modular synthetic stock",
        "Single-stage trigger",
        "Metallic bolt shroud",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "2.0-4.0 lbs adjustable",
        safetyFeatures: ["Two-Position Safety"],
        magazines: "Ships with 1 detachable magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.9,
      reviews: 43,
    },
    {
      id: 24,
      name: "Mossberg Patriot Predator",
      description:
        "Purpose-built hunting rifle with threaded barrel and camo finish. Designed for predator and varmint hunting.",
      price: 449.99,
      originalPrice: 499.99,
      category: "rifles",
      stock: 9,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Mossberg",
      caliber: ".223 Remington",
      capacity: "5+1",
      barrelLength: "22 inches (threaded)",
      overallLength: "42 inches",
      weight: "6.5 lbs",
      action: "Bolt-Action",
      finish: "Mossy Oak Break-Up Country Camo",
      sights: "None - Scope Rail Included",
      features: [
        "Threaded barrel for suppressor",
        "LBA adjustable trigger",
        "Spiral fluted bolt",
        "Box magazine fed",
        "Mossy Oak camo finish",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "2.0-7.0 lbs adjustable",
        safetyFeatures: ["Two-Position Safety"],
        magazines: "Ships with 1 detachable magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.4,
      reviews: 61,
    },
    {
      id: 25,
      name: "Bergara B-14 Hunter",
      description:
        "Spanish precision manufacturing meets American hunting traditions. Sub-MOA accuracy guarantee.",
      price: 849.99,
      category: "rifles",
      stock: 6,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Bergara",
      caliber: "6.5 Creedmoor",
      capacity: "4+1",
      barrelLength: "22 inches",
      overallLength: "42.5 inches",
      weight: "7.3 lbs",
      action: "Bolt-Action",
      finish: "Matte Black Cerakote",
      sights: "None - Drilled & Tapped",
      features: [
        "Match-grade barrel",
        "Sub-MOA accuracy guarantee",
        "Bergara Performance trigger",
        "Synthetic stock with SoftTouch",
        "Hinged floorplate",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "3.0-4.0 lbs",
        safetyFeatures: ["Two-Position Safety"],
        magazines: "Internal magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.8,
      reviews: 37,
    },
    {
      id: 26,
      name: "CZ 455 American",
      description:
        "Czech precision in .22 LR. Adjustable trigger and interchangeable barrel system for versatility.",
      price: 459.99,
      category: "rifles",
      stock: 11,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "CZ",
      caliber: ".22 Long Rifle",
      capacity: "5+1",
      barrelLength: "20.5 inches",
      overallLength: "39.5 inches",
      weight: "6.1 lbs",
      action: "Bolt-Action",
      finish: "Blued",
      sights: "Hooded Front / Tangent Rear",
      features: [
        "Adjustable trigger",
        "Interchangeable barrel system",
        "American pattern stock",
        "Detachable magazine",
        "Cold hammer-forged barrel",
      ],
      specifications: {
        frameSize: "Standard",
        triggerPull: "2.2-3.3 lbs adjustable",
        safetyFeatures: ["Two-Position Safety"],
        magazines: "Ships with 1 detachable magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.7,
      reviews: 29,
    },
    {
      id: 27,
      name: "Weatherby Vanguard Series 2",
      description:
        "Sub-MOA accuracy guarantee with hand-lapped barrel. Premium hunting rifle with Monte Carlo stock.",
      price: 649.99,
      originalPrice: 699.99,
      category: "rifles",
      stock: 4,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["rifles"],
      manufacturer: "Weatherby",
      caliber: ".300 Winchester Magnum",
      capacity: "3+1",
      barrelLength: "26 inches",
      overallLength: "46.75 inches",
      weight: "7.75 lbs",
      action: "Bolt-Action",
      finish: "Matte Bead Blast",
      sights: "None - Drilled & Tapped",
      features: [
        "Sub-MOA accuracy guarantee",
        "Hand-lapped barrel",
        "Two-stage trigger",
        "Monte Carlo stock",
        "Hinged floorplate",
      ],
      specifications: {
        frameSize: "Magnum",
        triggerPull: "3.5-5.0 lbs",
        safetyFeatures: ["Three-Position Safety"],
        magazines: "Internal magazine",
        warranty: "Sub-MOA Accuracy Guarantee",
      },
      inStock: true,
      onSale: true,
      rating: 4.6,
      reviews: 52,
    },
    // SHOTGUN COLLECTION
    {
      id: 28,
      name: "Remington 870 Express",
      description:
        "America's most popular pump-action shotgun. Legendary reliability for hunting, home defense, and sport shooting with over 11 million sold worldwide.",
      price: 449.99,
      originalPrice: 499.99,
      category: "shotguns",
      stock: 12,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "shotguns"],
      manufacturer: "Remington",
      gauge: "12 Gauge",
      capacity: "4+1",
      barrelLength: "28 inches",
      overallLength: "48.5 inches",
      weight: "7.25 lbs",
      action: "Pump-Action",
      finish: "Matte Black",
      chokes: "Modified Rem Choke",
      features: [
        "Twin action bars for smooth operation",
        "Cross-bolt safety",
        "Interchangeable Rem Choke system",
        "Hardwood stock and forend",
        "Steel receiver",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "6.0-8.0 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Loading Gate"],
        magazines: "Tubular magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 389,
    },
    {
      id: 29,
      name: "Mossberg 500",
      description:
        "Versatile and dependable pump-action shotgun with dual extractors and positive steel-to-steel lockup. Perfect for hunting and tactical applications.",
      price: 399.99,
      category: "shotguns",
      stock: 15,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "shotguns"],
      manufacturer: "Mossberg",
      gauge: "12 Gauge",
      capacity: "5+1",
      barrelLength: "28 inches",
      overallLength: "48 inches",
      weight: "7.5 lbs",
      action: "Pump-Action",
      finish: "Blue",
      chokes: "Accu-Choke (Modified)",
      features: [
        "Dual extractors",
        "Positive steel-to-steel lockup",
        "Top-mounted safety",
        "Ambidextrous design",
        "Easy takedown",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "5.5-7.5 lbs",
        safetyFeatures: ["Top-Mounted Safety", "Trigger Disconnect"],
        magazines: "Tubular magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.6,
      reviews: 267,
    },
    {
      id: 30,
      name: "Benelli Super Black Eagle 3",
      description:
        "Premium semi-automatic shotgun with comfort tech technology and inertia-driven system. The ultimate waterfowl and upland game gun.",
      price: 1699.99,
      originalPrice: 1799.99,
      category: "shotguns",
      stock: 6,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["shotguns"],
      manufacturer: "Benelli",
      gauge: "12 Gauge",
      capacity: "3+1",
      barrelLength: "28 inches",
      overallLength: "49.6 inches",
      weight: "7.0 lbs",
      action: "Semi-Automatic",
      finish: "Black Synthetic",
      chokes: "Crio Chokes (IC, M, F)",
      features: [
        "ComforTech stock technology",
        "Inertia Driven system",
        "Easy loading system",
        "Red bar front sight",
        "Crio barrel treatment",
      ],
      specifications: {
        chamberLength: "3.5 inches",
        triggerPull: "4.5-6.0 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Loading Gate Safety"],
        magazines: "Tubular magazine",
        warranty: "5-Year Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.9,
      reviews: 156,
    },
    {
      id: 31,
      name: "Beretta A400 Xtreme Plus",
      description:
        "Advanced semi-automatic with Kick-Off technology and Optima-Bore barrels. Built for extreme conditions and maximum reliability.",
      price: 1849.99,
      category: "shotguns",
      stock: 4,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Beretta",
      gauge: "12 Gauge",
      capacity: "3+1",
      barrelLength: "28 inches",
      overallLength: "49.6 inches",
      weight: "7.25 lbs",
      action: "Semi-Automatic",
      finish: "Max-5 Camo",
      chokes: "Optima-Choke HP (IC, M, F)",
      features: [
        "Kick-Off recoil reduction",
        "Blink gas operating system",
        "Optima-Bore barrel",
        "Gun Pod compatibility",
        "Steelium barrel technology",
      ],
      specifications: {
        chamberLength: "3.5 inches",
        triggerPull: "4.0-5.5 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Bolt Hold-Open"],
        magazines: "Tubular magazine",
        warranty: "3-Year Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.8,
      reviews: 89,
    },
    {
      id: 32,
      name: "Winchester SXP Defender",
      description:
        "Tactical pump-action shotgun with speed pump system. Fast, reliable, and built for home defense and law enforcement applications.",
      price: 349.99,
      originalPrice: 399.99,
      category: "shotguns",
      stock: 10,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Winchester",
      gauge: "12 Gauge",
      capacity: "5+1",
      barrelLength: "18 inches",
      overallLength: "39 inches",
      weight: "6.75 lbs",
      action: "Pump-Action",
      finish: "Matte Black",
      chokes: "Cylinder Bore",
      features: [
        "Speed Pump system",
        "Ribbed forearm",
        "Textured gripping surfaces",
        "TruGlo front sight",
        "Picatinny rail",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "5.0-7.0 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Action Release"],
        magazines: "Tubular magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.5,
      reviews: 124,
    },
    {
      id: 33,
      name: "CZ-USA 612 Magnum",
      description:
        "Turkish-made semi-automatic with gas-operated system. Reliable performance for waterfowl hunting with 3.5-inch magnum capability.",
      price: 549.99,
      category: "shotguns",
      stock: 8,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "CZ-USA",
      gauge: "12 Gauge",
      capacity: "4+1",
      barrelLength: "28 inches",
      overallLength: "49 inches",
      weight: "7.3 lbs",
      action: "Semi-Automatic",
      finish: "Matte Black Synthetic",
      chokes: "5 Flush-Mount Chokes",
      features: [
        "Gas-operated system",
        "Chrome-lined barrel",
        "Fiber optic front sight",
        "Extended bolt handle",
        "3.5-inch magnum capability",
      ],
      specifications: {
        chamberLength: "3.5 inches",
        triggerPull: "5.0-6.5 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Bolt Lock"],
        magazines: "Tubular magazine",
        warranty: "5-Year Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.4,
      reviews: 67,
    },
    {
      id: 34,
      name: "Savage 555 Over/Under",
      description:
        "Affordable over/under shotgun with extractors and Turkish walnut stock. Perfect entry-level double barrel for sporting clays and hunting.",
      price: 699.99,
      originalPrice: 749.99,
      category: "shotguns",
      stock: 7,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Savage",
      gauge: "20 Gauge",
      capacity: "2",
      barrelLength: "28 inches",
      overallLength: "45 inches",
      weight: "6.5 lbs",
      action: "Over/Under",
      finish: "Blue with Turkish Walnut",
      chokes: "5 Beretta/Benelli Mobil chokes",
      features: [
        "Single selective trigger",
        "Manual extractors",
        "Turkish walnut stock",
        "Fiber optic front sight",
        "Lightweight aluminum receiver",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "4.5-6.0 lbs",
        safetyFeatures: ["Manual Safety", "Barrel Selector"],
        magazines: "N/A (Break-Action)",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.3,
      reviews: 45,
    },
    {
      id: 35,
      name: "Stoeger M3000",
      description:
        "Inertia-driven semi-automatic shotgun with red fiber optic sight. Reliable and affordable for all hunting applications.",
      price: 599.99,
      category: "shotguns",
      stock: 9,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Stoeger",
      gauge: "12 Gauge",
      capacity: "4+1",
      barrelLength: "26 inches",
      overallLength: "47 inches",
      weight: "7.3 lbs",
      action: "Semi-Automatic",
      finish: "Black Synthetic",
      chokes: "3 choke tubes (IC, M, XFT)",
      features: [
        "Inertia Driven system",
        "Red fiber optic sight",
        "Drilled and tapped receiver",
        "Shim kit included",
        "Easy maintenance",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "5.0-6.5 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Half-Cock Notch"],
        magazines: "Tubular magazine",
        warranty: "5-Year Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.2,
      reviews: 78,
    },
    {
      id: 36,
      name: "Franchi Affinity 3",
      description:
        "Lightweight semi-automatic with TSA recoil pad and Inertia Driven system. Perfect balance of performance and comfort for upland hunting.",
      price: 849.99,
      originalPrice: 899.99,
      category: "shotguns",
      stock: 6,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Franchi",
      gauge: "20 Gauge",
      capacity: "4+1",
      barrelLength: "26 inches",
      overallLength: "46.5 inches",
      weight: "5.7 lbs",
      action: "Semi-Automatic",
      finish: "Satin Walnut",
      chokes: "3 Extended chokes (IC, M, F)",
      features: [
        "TSA recoil pad",
        "Inertia Driven system",
        "AA-grade satin walnut",
        "Red fiber optic sight",
        "Ergonomic design",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "4.5-5.5 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Drop Safety"],
        magazines: "Tubular magazine",
        warranty: "7-Year Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.6,
      reviews: 52,
    },
    {
      id: 37,
      name: "Browning Citori 725",
      description:
        "Premium over/under shotgun with mechanical trigger and low-profile receiver. The gold standard for sporting clays and competition shooting.",
      price: 2299.99,
      category: "shotguns",
      stock: 3,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Browning",
      gauge: "12 Gauge",
      capacity: "2",
      barrelLength: "30 inches",
      overallLength: "47 inches",
      weight: "7.7 lbs",
      action: "Over/Under",
      finish: "Grade III/IV Walnut",
      chokes: "Invector-DS chokes (5)",
      features: [
        "Mechanical trigger system",
        "Low-profile receiver",
        "Vector Pro lengthened forcing cones",
        "Ivory front and mid-bead sights",
        "Grade III/IV walnut stock",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "4.0-5.0 lbs",
        safetyFeatures: ["Manual Safety", "Barrel Selector"],
        magazines: "N/A (Break-Action)",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.9,
      reviews: 34,
    },
    {
      id: 38,
      name: "Weatherby SA-08",
      description:
        "Gas-operated semi-automatic with chrome-lined barrel and drop-out trigger system. Reliable performance for hunting and sport shooting.",
      price: 649.99,
      originalPrice: 699.99,
      category: "shotguns",
      stock: 8,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Weatherby",
      gauge: "12 Gauge",
      capacity: "4+1",
      barrelLength: "28 inches",
      overallLength: "48 inches",
      weight: "6.75 lbs",
      action: "Semi-Automatic",
      finish: "Matte Black Synthetic",
      chokes: "3 choke tubes (IC, M, F)",
      features: [
        "Gas-operated system",
        "Chrome-lined barrel",
        "Drop-out trigger system",
        "Dual valve system",
        "Easy maintenance",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "5.0-6.0 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Action Lock"],
        magazines: "Tubular magazine",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.4,
      reviews: 61,
    },
    {
      id: 39,
      name: "Tristar Viper G2",
      description:
        "Affordable semi-automatic with gas-operated system and chrome-lined barrel. Great value for money with reliable cycling.",
      price: 429.99,
      category: "shotguns",
      stock: 11,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["shotguns"],
      manufacturer: "Tristar",
      gauge: "20 Gauge",
      capacity: "4+1",
      barrelLength: "26 inches",
      overallLength: "46 inches",
      weight: "6.4 lbs",
      action: "Semi-Automatic",
      finish: "Black Synthetic",
      chokes: "3 Beretta/Benelli Mobil chokes",
      features: [
        "Gas-operated system",
        "Chrome-lined barrel",
        "Soft touch coating",
        "Fiber optic front sight",
        "Easy loading port",
      ],
      specifications: {
        chamberLength: "3 inches",
        triggerPull: "5.5-6.5 lbs",
        safetyFeatures: ["Cross-Bolt Safety", "Loading Gate"],
        magazines: "Tubular magazine",
        warranty: "5-Year Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.1,
      reviews: 43,
    },
    // ACCESSORIES COLLECTION
    {
      id: 3,
      name: "Vortex Viper PST Gen II 1-6x24",
      description:
        "Professional tactical scope with first focal plane reticle and crystal-clear glass. Perfect for precision shooting and tactical applications with exceptional light transmission.",
      price: 699.99,
      originalPrice: 799.99,
      category: "accessories",
      stock: 15,
      images: [
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["home", "featured", "accessories"],
      manufacturer: "Vortex",
      type: "Variable Power Scope",
      magnification: "1-6x24mm",
      reticle: "EBR-4 MOA",
      tubeSize: "30mm",
      length: "10.5 inches",
      weight: "21.2 oz",
      features: [
        "First focal plane reticle",
        "XD lens elements",
        "XR fully multi-coated",
        "Capped low-profile turrets",
        "Single-piece tube construction",
      ],
      specifications: {
        eyeRelief: "3.5 inches",
        fieldOfView: "116-19.2 feet@100 yards",
        clickValue: "1/4 MOA",
        waterproof: "IPX7 rated",
        warranty: "VIP Lifetime Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.8,
      reviews: 234,
    },
    {
      id: 40,
      name: "Aimpoint PRO Red Dot Sight",
      description:
        "Professional grade red dot sight with 30,000-hour battery life. Built for law enforcement and military use with legendary Aimpoint reliability.",
      price: 449.99,
      category: "accessories",
      stock: 22,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["accessories"],
      manufacturer: "Aimpoint",
      type: "Red Dot Sight",
      magnification: "1x",
      reticle: "2 MOA Red Dot",
      tubeSize: "30mm",
      length: "4.5 inches",
      weight: "7.8 oz",
      features: [
        "30,000-hour battery life",
        "Flip-up lens covers",
        "QRP2 mount included",
        "Night vision compatible",
        "Waterproof to 150 feet",
      ],
      specifications: {
        batteryLife: "30,000 hours",
        operatingTemp: "-45°F to +160°F",
        clickValue: "1/2 MOA",
        waterproof: "150 feet submersible",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.9,
      reviews: 456,
    },
    {
      id: 41,
      name: "Surefire X300 Ultra Weapon Light",
      description:
        "High-output LED weapon light delivering 1,000 lumens of stunning white light. Built for professionals who demand reliability in critical situations.",
      price: 279.99,
      originalPrice: 319.99,
      category: "accessories",
      stock: 18,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["accessories"],
      manufacturer: "Surefire",
      type: "Weapon Light",
      output: "1,000 lumens",
      runtime: "1.25 hours",
      length: "4.0 inches",
      weight: "4.0 oz",
      beamDistance: "200 meters",
      features: [
        "Ambidextrous switching",
        "Rail-grabbing claws",
        "Precision reflector",
        "Tactical tailcap",
        "Impact resistant",
      ],
      specifications: {
        battery: "2x CR123A",
        material: "Aerospace aluminum",
        finish: "Mil-Spec anodizing",
        waterproof: "IPX7 rated",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 189,
    },
    {
      id: 42,
      name: "Magpul PMAG 30 AR M4 Gen M3",
      description:
        "Lightweight, cost-effective polymer magazine for AR-15/M4 platforms. Featuring anti-tilt follower and constant-curve geometry for reliable feeding.",
      price: 14.99,
      category: "accessories",
      stock: 150,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Magpul",
      type: "Magazine",
      capacity: "30 rounds",
      material: "Polymer",
      compatibility: "AR-15/M4",
      length: "7.3 inches",
      weight: "4.2 oz",
      features: [
        "Anti-tilt follower",
        "Constant-curve geometry",
        "Impact resistant polymer",
        "Flared floorplate",
        "Dust/impact cover",
      ],
      specifications: {
        temperature: "-50°F to +180°F",
        rounds: "30",
        material: "Impact-resistant polymer",
        finish: "Textured surface",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.6,
      reviews: 892,
    },
    {
      id: 43,
      name: "Harris S-BRM Bipod",
      description:
        "Professional shooting bipod with notched legs and swivel stud mount. Built for precision shooting with adjustable height and cant adjustment.",
      price: 99.99,
      originalPrice: 119.99,
      category: "accessories",
      stock: 35,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Harris",
      type: "Bipod",
      height: "6-9 inches",
      weight: "13 oz",
      material: "Aluminum",
      legs: "Notched",
      mount: "Swivel Stud",
      features: [
        "Spring-return telescoping legs",
        "Completely adjustable",
        "Rubber feet with retractable spikes",
        "Lightweight aluminum construction",
        "Attaches to swivel stud",
      ],
      specifications: {
        heightRange: "6-9 inches",
        legMaterial: "Aluminum",
        mounting: "Swivel stud",
        adjustability: "Notched legs",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.5,
      reviews: 267,
    },
    {
      id: 44,
      name: "Streamlight TLR-1 HL",
      description:
        "High-lumen tactical light with strobe function. Featuring C4 LED technology and ambidextrous switching for versatile weapon mounting.",
      price: 139.99,
      category: "accessories",
      stock: 28,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Streamlight",
      type: "Tactical Light",
      output: "800 lumens",
      runtime: "1.25 hours",
      length: "3.39 inches",
      weight: "4.18 oz",
      beamDistance: "283 meters",
      features: [
        "C4 LED technology",
        "Strobe function",
        "Rail clamp system",
        "Ambidextrous switching",
        "Impact resistant",
      ],
      specifications: {
        battery: "2x CR123A",
        beamType: "Concentrated",
        runtime: "1.25 hours continuous",
        waterproof: "IPX7 rated",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.4,
      reviews: 156,
    },
    {
      id: 45,
      name: "Leupold VX-3HD 3.5-10x40",
      description:
        "Premium hunting scope with HD optical system and CDS turret system. Engineered for hunters who demand crystal-clear optics and reliable performance.",
      price: 499.99,
      originalPrice: 549.99,
      category: "accessories",
      stock: 12,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Leupold",
      type: "Hunting Scope",
      magnification: "3.5-10x40mm",
      reticle: "Duplex",
      tubeSize: "1 inch",
      length: "12.6 inches",
      weight: "12.1 oz",
      features: [
        "HD optical system",
        "CDS turret system",
        "Twilight Max HD coating",
        "Side focus parallax",
        "Second focal plane",
      ],
      specifications: {
        eyeRelief: "4.4-3.6 inches",
        fieldOfView: "29.4-10.4 feet@100 yards",
        clickValue: "1/4 MOA",
        waterproof: "Fully waterproof",
        warranty: "Full Lifetime Guarantee",
      },
      inStock: true,
      onSale: true,
      rating: 4.8,
      reviews: 123,
    },
    {
      id: 46,
      name: "Troy M4 Carbine Length Rail",
      description:
        "Lightweight modular rail system with KeyMod mounting technology. Precision-machined from aircraft-grade aluminum for maximum durability.",
      price: 189.99,
      category: "accessories",
      stock: 20,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Troy",
      type: "Rail System",
      length: "Carbine Length",
      material: "Aircraft Aluminum",
      mounting: "KeyMod",
      weight: "7.8 oz",
      compatibility: "AR-15",
      features: [
        "KeyMod mounting system",
        "Aircraft-grade aluminum",
        "Continuous top rail",
        "Anti-rotation design",
        "Tool-free installation",
      ],
      specifications: {
        material: "6061-T6 aluminum",
        finish: "Hard coat anodized",
        railStandard: "MIL-STD-1913",
        mounting: "KeyMod compatible",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.3,
      reviews: 89,
    },
    {
      id: 47,
      name: "EOTech XPS2 Holographic Sight",
      description:
        "Compact holographic weapon sight with instant target acquisition. Features side button controls and unlimited eye relief for tactical applications.",
      price: 529.99,
      originalPrice: 579.99,
      category: "accessories",
      stock: 16,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "EOTech",
      type: "Holographic Sight",
      reticle: "68 MOA Ring & 1 MOA Dot",
      batteryLife: "600 hours",
      length: "3.8 inches",
      weight: "9 oz",
      eyeRelief: "Unlimited",
      features: [
        "True holographic technology",
        "Side button controls",
        "Water resistant",
        "Fog resistant",
        "Quick detach lever",
      ],
      specifications: {
        battery: "1x CR123A",
        operatingTemp: "-40°F to +140°F",
        waterRating: "10 feet for 2 hours",
        reticlePattern: "68 MOA ring with 1 MOA dot",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: true,
      rating: 4.7,
      reviews: 201,
    },
    {
      id: 48,
      name: "Magpul MOE Stock",
      description:
        "Mil-Spec carbine stock with improved cheek weld and shoulder pocket. Features enhanced butt-pad and sling attachment point for comfort and functionality.",
      price: 49.99,
      category: "accessories",
      stock: 45,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Magpul",
      type: "Carbine Stock",
      material: "Polymer",
      compatibility: "Mil-Spec Buffer Tube",
      weight: "8.8 oz",
      length: "7.25 inches",
      pullLength: "13.5 inches",
      features: [
        "Improved cheek weld",
        "Enhanced shoulder pocket",
        "0.30-inch thick butt-pad",
        "Ambidextrous sling attachment",
        "Storage compartment",
      ],
      specifications: {
        bufferTube: "Mil-Spec carbine",
        material: "Impact-resistant polymer",
        finish: "Textured surface",
        temperature: "-50°F to +180°F",
        warranty: "Limited Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.4,
      reviews: 334,
    },
    {
      id: 49,
      name: "Trijicon ACOG 4x32",
      description:
        "Combat-proven optical gunsight with fiber optic illumination. Battle-tested design with Bindon Aiming Concept for rapid target engagement.",
      price: 1299.99,
      category: "accessories",
      stock: 8,
      images: [
        "https://images.unsplash.com/photo-1544717684-4b0c7db5b03a?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
      ],
      featured: true,
      displayLocation: ["accessories"],
      manufacturer: "Trijicon",
      type: "Combat Optic",
      magnification: "4x32mm",
      reticle: "Red Chevron BAC",
      length: "5.8 inches",
      weight: "9.9 oz",
      eyeRelief: "1.5 inches",
      features: [
        "Fiber optic illumination",
        "Bindon Aiming Concept",
        "Combat-proven design",
        "Bullet drop compensation",
        "No batteries required",
      ],
      specifications: {
        fieldOfView: "28.9 feet@100 yards",
        illumination: "Fiber optic & tritium",
        waterproof: "33 feet",
        temperature: "-40°F to +140°F",
        warranty: "Limited Lifetime Warranty",
      },
      inStock: true,
      onSale: false,
      rating: 4.9,
      reviews: 167,
    },
    {
      id: 50,
      name: "Pelican 1750 Rifle Case",
      description:
        "Watertight rifle case with pick-n-pluck foam and pressure relief valve. Built for extreme conditions with lifetime guarantee of excellence.",
      price: 349.99,
      originalPrice: 399.99,
      category: "accessories",
      stock: 14,
      images: [
        "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
        "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=300&fit=crop",
      ],
      featured: false,
      displayLocation: ["accessories"],
      manufacturer: "Pelican",
      type: "Rifle Case",
      interior: "53.75 x 13.5 x 5 inches",
      exterior: "56.13 x 17.12 x 6.12 inches",
      weight: "19.7 lbs",
      material: "Polypropylene",
      foam: "Pick-n-Pluck",
      features: [
        "Watertight seal",
        "Pick-n-pluck foam",
        "Pressure relief valve",
        "Stainless steel hardware",
        "Double-throw latches",
      ],
      specifications: {
        waterproof: "IP67 rated",
        temperature: "-40°F to +210°F",
        crushProof: "Yes",
        airline: "Approved",
        warranty: "Lifetime Guarantee",
      },
      inStock: true,
      onSale: true,
      rating: 4.6,
      reviews: 78,
    },
  ],

  // Orders
  orders: [
    {
      id: 1,
      customerId: 1,
      customerName: "John Doe",
      customerEmail: "john@example.com",
      items: [{ productId: 1, quantity: 1, price: 599.99 }],
      total: 599.99,
      status: "pending",
      date: "2024-01-15",
    },
  ],

  // Users
  users: [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      phone: "(555) 123-4567",
      address: "123 Main St, City, State 12345",
      registrationDate: "2024-01-10",
    },
  ],

  // Messages
  messages: [
    {
      id: 1,
      name: "Jane Smith",
      email: "jane@example.com",
      subject: "Product Inquiry",
      message: "I'm interested in the Glock 19. Is it still available?",
      date: "2024-01-15",
      read: false,
    },
  ],

  // Site Settings
  siteSettings: {
    siteName: "Gun-k",
    bankDetails: {
      bankName: "First National Bank",
      accountNumber: "****-****-1234",
      routingNumber: "021000021",
    },
    contactInfo: {
      email: "info@gunstore.com",
      phone: "(555) 123-4567",
      address: "123 Gun Store Ave, City, State 12345",
    },
    aboutUs:
      "We are a professional firearms dealer committed to providing quality products and exceptional service.",
    headerText: "Your Trusted Firearms Dealer",
    footerText: "Licensed FFL Dealer - All federal and state laws apply",
  },
};

function appReducer(state, action) {
  switch (action.type) {
    case "LOGIN_ADMIN":
      return { ...state, isAdminAuthenticated: true };

    case "LOGOUT_ADMIN":
      return { ...state, isAdminAuthenticated: false };

    case "ADD_PRODUCT":
      return {
        ...state,
        products: [...state.products, { ...action.payload, id: Date.now() }],
      };

    case "UPDATE_PRODUCT":
      return {
        ...state,
        products: state.products.map((p) =>
          p.id === action.payload.id ? action.payload : p,
        ),
      };

    case "DELETE_PRODUCT":
      return {
        ...state,
        products: state.products.filter((p) => p.id !== action.payload),
      };

    case "UPDATE_ORDER_STATUS":
      return {
        ...state,
        orders: state.orders.map((o) =>
          o.id === action.payload.id
            ? { ...o, status: action.payload.status }
            : o,
        ),
      };

    case "ADD_ORDER":
      return {
        ...state,
        orders: [...state.orders, { ...action.payload, id: Date.now() }],
      };

    case "ADD_USER":
      return {
        ...state,
        users: [...state.users, { ...action.payload, id: Date.now() }],
      };

    case "DELETE_USER":
      return {
        ...state,
        users: state.users.filter((u) => u.id !== action.payload),
      };

    case "ADD_MESSAGE":
      return {
        ...state,
        messages: [
          ...state.messages,
          { ...action.payload, id: Date.now(), read: false },
        ],
      };

    case "MARK_MESSAGE_READ":
      return {
        ...state,
        messages: state.messages.map((m) =>
          m.id === action.payload ? { ...m, read: true } : m,
        ),
      };

    case "UPDATE_SITE_SETTINGS":
      return {
        ...state,
        siteSettings: { ...state.siteSettings, ...action.payload },
      };

    case "LOAD_STATE":
      return { ...state, ...action.payload };

    default:
      return state;
  }
}

export function AppProvider({ children }) {
  const [state, dispatch] = useReducer(appReducer, initialState);

  // Load state from localStorage on mount
  useEffect(() => {
    const savedState = localStorage.getItem("gunStoreState");
    if (savedState) {
      try {
        const parsedState = JSON.parse(savedState);
        dispatch({ type: "LOAD_STATE", payload: parsedState });
      } catch (error) {
        console.error("Error loading saved state:", error);
      }
    }
  }, []);

  // Save state to localStorage on state changes
  useEffect(() => {
    localStorage.setItem("gunStoreState", JSON.stringify(state));
  }, [state]);

  return (
    <AppContext.Provider value={{ state, dispatch }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within an AppProvider");
  }
  return context;
}
